const CONSTANT = {
  SCROLL_WAIT_TIME: 300,
  FIVE_MINUTE_IN_MILLISECONDS: 5 * 60 * 1000,
  YOUTUBE_URL: "https://www.youtube.com/watch?v=",
  LANGUAGE_OPTIONS: [
    "javascript",
    "html",
    "css",
    "python",
    "php",
    "go",
    "cpp",
    "csharp",
    "mysql",
    "scss",
    "sql",
    "yml",
    "xml",
    "dart",
    "swift",
    "kotlin",
    "markdown",
    "typescript",
    "java",
    "ruby",
    "rust",
    "shell",
  ],
};

export default CONSTANT;
